eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: oaith2-hi
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8762/users/current
    client:
      id: client_1
      client-secret: 123456
      access-token-uri: http://localhost:8762/oauth/token
      grant-type: password,refresh_token
      scope: all