server:
  port: 8762
spring:
  application:
    name: oauth2-server
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/